In [2]:
import numpy as np

1 - Representing and Solving a System of Linear Equations using Matrices

1.1 - System of Linear Equations

Here is a system of linear equations (or linear system) with three equations and three unknown variables:

                        {
                            4x1 - 3x2 + x3 = -10,
                            2x1 + x2 + 3x3 = 0,        -(1)
                            -x1 + 2x2 - 5x3 = 17
                        }

To solve this system of linear equations means to find such values of the variables x1, x2, x3, that all of its equations are simultaneously satisfied.

1.2 - Solving Systems of Linear Equations using Matrices

Let's prepare to solve the linear system (1)
 using NumPy. A will be a matrix, each row will represent one equation in the system and each column will correspond to the variable x1, x2, x3. And b is a 1-D array of the free (right side) coefficients:

In [3]:
A = np.array([[4, -3, 1],
             [2, 1, 3],
             [-1, 2, -5]], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


Check the dimnesions of A and b using shape() function:

In [4]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

Shape of A: (3, 3)
Shape of b: (3,)


Now use np.linalg.solve(A, b) function to find the solution of the system (1). The result will be saved in the 1-D array x. The elements will correspond to the values of x1, x2 and x3:

In [5]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


1.3 - Evaluating the Determinant of a Matrix

Matrix A corresponding to the linear system (1) is a square matrix - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix A has a non-zero determinant.

Let's calculate the determinant using np.linalg.det(A) function:

In [6]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -60.00


2 - Solving System of Linear Equations using Row Reduction

2.1 - Preparation for Row Reduction

You can see how easy it is to use contemporary packages to solve linear equations. However, for a deeper understanding of mathematical concepts, it is important to practice some solution techniques manually. The programming approach can still help here to reduce the number of arithmetical calculations, and focus on the method itself.

Here you can practice the row reduction method for the linear system with three variables. To apply it, first, unify matrix A and array b into one matrix using np.hstack() function. Note that the shape of the originally defined array was (3,), to stack it with the (3,3) matrix you need to transform it so that it has the same number of dimensions. You can use .reshape((3, 1)) function:

In [7]:
A_system = np.hstack((A, b.reshape(3, 1)))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


2.2 - Functions for Elementary Operations

Let's review elementary operations, which do not change the solution set of a linear system:

1) Multiply any row by a non-zero number
2) Add two rows and exchange one of the original rows with the result of the addition
3) Swap rows

In the case of larger systems you will need to apply elementary operations multiple times. Thus, it is convenient to define the corresponding Python functions. Investigate them in the following code cells with the examples:

In [8]:
# Exchange row_num of the Matrix M with its multiple by row_multiple
# Note: for simplicity, you can drop check if row_num has non-zero value, which makes the operation valid
def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

print("Original Matrix:")
print(A_system)
print("\nMatrix after its 3rd row is multiplied by 2:")
print(MultiplyRow(A_system, 2, 2))

Original Matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after its 3rd row is multiplied by 2:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [9]:
# Multiply row_num_1 by row_num_1_multiple and add it to row_num_2
# Exchanging row_num_2 of the Matrix M in the result
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = M_new[row_num_2] + M_new[row_num_1]*row_num_1_multiple
    return M_new

print("Original Matrix:")
print(A_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(A_system, 1, 2, 1/2))

Original Matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [10]:
# Exchange row_num_1 of the Matrix M with its row_num_2
def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

print("Original Matrix:")
print(A_system)
print("\nMatrix after exchange of its first and third rows:")
print(SwapRows(A_system, 0, 2))

Original Matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of its first and third rows:
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


2.3 - Row Reduction and Solution of the Linear System

Now you can use the defined operations to bring the matrix into row reduced form. To do this manually, it is convenient to have 1 or -1 value in the first element of the first row (the arithmetics of operations is easier then).Performing calculations in Python, won't provide much of a benefit, but it is better to do that for illustration purposes. So, let's swap the first and third rows:

In [11]:
A_ref = SwapRows(A_system, 0, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


Now you would need to make such elementary operations, that the first elements in the second and third row become equal to zero:

In [12]:
# Mutiply row 0 of new matrix A_ref 2 and add it to row 1
A_ref = AddRows(A_ref, 0, 1, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [13]:
# Multiply row 0 of new matrix A_ref by 4 and add it to row 2
A_ref = AddRows(A_ref, 0, 2, 4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


The next step will be to perform an operation by putting the second element in the third row equal to zero:

In [14]:
# Multiply row 1 of the new matrix A_ref by -1 and add it to row 2
A_ref = AddRows(A_ref, 1, 2, -1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]



It is easy now to find the value of x3 from the third row, as it corresponds to the equation -12x3 = 24. Let's divide the row by -12:

In [15]:
A_ref = MultiplyRow(A_ref, 2, -1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


Now the second row of the matrix corresponds to the equation 5x2 - 7x3 = 34 and the first row to the equation -x1 + 2x2 -5x3 = 17. Referring to the elements of the matrix, you can find the values of x2 and x1.

In [18]:
x_3 = -2.0
x_2 = (A_ref[1, 3] - [A_ref[1, 2]*x_3]) / A_ref[1, 1]
x_1 = (A_ref[0, 3] - A_ref[0, 2]*x_3 - A_ref[0, 1]*x_2) / A_ref[0, 0]

print(x_1[0], x_2[0], x_3)

1.0 4.0 -2.0


3 - System of Linear Equations with No Solutions

Given another system of linear equations:

                {
                x1 + x2 + x3 = 2,
                x2 - 3x3 = 1,            (2)
                2x1 + x2 + 5x3 = 0,
                }

let's find the determinant of the corresponding matrix.

In [20]:
A_2 = np.array([[1, 1, 1],
                [0, 1, -3],
                [2, 1, 5]],
                dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)
print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


It is equal to zero, thus the system cannot have one unique solution. It will have either infinitely many solutions or none. The consistency of it will depend on the free coefficients (right side coefficients). You can uncomment and run the code in the following cell to check that the np.linalg.solve() function will give an error due to singularity.

In [23]:
# x_2 = np.linalg.solve(A_2, b_2)