In [1]:
import numpy as np

1 - Representing and Solving a System of Linear Equations using Matrices

1.1 - System of Linear Equations

Here is a system of linear equations (or linear system) with three equations and three unknown variables:

                        {
                            4x1 - 3x2 + x3 = -10,
                            2x1 + x2 + 3x3 = 0,        -(1)
                            -x1 + 2x2 - 5x3 = 17
                        }

To solve this system of linear equations means to find such values of the variables x1, x2, x3, that all of its equations are simultaneously satisfied.

1.2 - Solving Systems of Linear Equations using Matrices

Let's prepare to solve the linear system (1)
 using NumPy. A will be a matrix, each row will represent one equation in the system and each column will correspond to the variable x1, x2, x3. And b is a 1-D array of the free (right side) coefficients:

In [7]:
A = np.array([[4, -3, 1],
             [2, 1, 3],
             [-1, 2, -5]], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


Check the dimnesions of A and b using shape() function:

In [8]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

Shape of A: (3, 3)
Shape of b: (3,)


Now use np.linalg.solve(A, b) function to find the solution of the system (1). The result will be saved in the 1-D array x. The elements will correspond to the values of x1, x2 and x3:

In [9]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [ 1.  4. -2.]
