In [2]:
import numpy as np

1 NumPy Basics

1.1  How to create NumPy arrays

1)  array()

In [3]:
# Create and print a 1-D array 'a' using array()
a = np.array([1, 2, 3])
print(a)

[1 2 3]


2.  arange() - Return an array of evenly spaced values within a given interval

In [4]:
# Create an array with 3 integers, starting from default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [5]:
# Create an array that starts from integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


3. linspace() - Here you specify the total number of points needed (num=10), and NumPy calculates the step size, whereas in arange you determine step size.

In [6]:
# Create an array that starts from 0, ends at 100 and has 5 elements in this range
d = np.linspace(0, 100, 5, dtype=int) #Not specifying dtype will return the values in float
print(d)

[  0  25  50  75 100]


In [7]:
char_arr = np.array(['Welcome to Math for ML'])
print(char_arr)
print(char_arr.dtype) 

['Welcome to Math for ML']
<U22


1.2  More on NumPy arrays

1) np.ones() - Returns a new array setting values to one.
2) np.zeros() - Returns a new array setting values to zero.
3) np.empty() - Returns a new uninitialized array.
4) np.random.rand() - Returns a new array with values chosen at random (between 0 and 1)

In [8]:
ones_arr = np.ones(3)
zeros_array = np.zeros(3)
empty_arr = np.empty(3)
rand_arr = np.random.rand(4)
print(ones_arr)
print(zeros_array)
print(empty_arr)
print(rand_arr)

[1. 1. 1.]
[0. 0. 0.]
[0. 0. 0.]
[0.86216724 0.25408953 0.81544148 0.76321359]


2  Multidimensional Arrays

Think: 
1) 1-D Array -- Vector or single ruler with markings
2) 2-D Array -- Matrix or Excel sheet
3) 3-D Array -- Stack of matrices

In [9]:
# Create a 2 dimensional array (2-D)
two_d_arr = np.array([[2, 3, 4], [2, 7, 5]])
print(two_d_arr)

[[2 3 4]
 [2 7 5]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using np.reshape() you can rearrange elements of the previous array into a new shape.

In [10]:
# 1-D array 
one_d_arr = np.array([4, 3, 9, 4, 2, 8])

# Multidimensional array using reshape()
multi_d_arr = np.reshape(
                one_d_arr, #Array to be reshaped
                (2, 3) # Dimensions of the new array
                    )
# Print the new 2-D array with 2 rows and 3 columns
print(multi_d_arr)

[[4 3 9]
 [4 2 8]]


2.1  Finding size, shape and dimension

1) ndarray.ndim - Stores the number dimensions of the array.
2) ndarray.shape - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
3) ndarray.size - Stores the number of elements in the array.

In [11]:
# Dimension of the 2-D array multi_d_arr
multi_d_arr.ndim

2

In [12]:
# Shape of the 2-D array multi_d_arr
multi_d_arr.shape

(2, 3)

In [13]:
# Size of the array multi_d_arr
multi_d_arr.size

6

3  Array Math Operations

In [14]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


3.1 - Multiplying vector with a scalar (brodcasting)

Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell.

This concept is called broadcasting, which allows you to perform operations specifically on arrays of different shapes.

In [15]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

4 - Indexing and Slicing

4.1 - Indexing

In [23]:
# Select the third element of the 1-D array. Remember the counting starts from 0.
a1 = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array
print(a1[0])

3
1


In [19]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]))

# Select element 6 from 2-D array using indices i, j 
print(two_dim[1][2])

6


4.2 Slicing

The syntax is:

array[start:end:step]

If no value is passed to start, it is assumed start = 0, if no value is passed to end, it is assumed that end = length of array - 1 and if no value is passed to step, it is assumed step = 1.

In [20]:
# Slice the array a1 to get the array [2, 3, 4]
sliced_arr = a1[1:4]
print(sliced_arr)

[2 3 4]


In [26]:
# Slice the two_dim array to get first 2 rows
sliced_arr_1 = two_dim[0:2]
print(sliced_arr_1)

[[1 2 3]
 [4 5 6]]


In [27]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [ ]:
# Print first two elements of every row of two_dim array
sliced_two_dim_cols = two_dim[:,0:2]
print(sliced_two_dim_cols)

[[1 2]
 [4 5]
 [7 8]]


5 - Stacking

1) np.vstack() - stacks vertically
2) np.hstack() - stacks horizontally
3) np.hsplit() - splits an array into several smaller arrays

In [33]:
n = np.array([[1, 1],
              [2, 2]])
s = np.array([[3, 3],
              [4, 4]])

print(f'{n}')
print(f'{s}')

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [34]:
# Stack the arrays vertically
vert_stack = np.vstack((n, s))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [35]:
# Stack the arrays horizontally
horz_stack = np.hstack((n, s))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
