In [1]:
import numpy as np

1 NumPy Basics

1.1  How to create NumPy arrays

1)  array()

In [2]:
# Create and print a 1-D array 'a' using array()
a = np.array([1, 2, 3])
print(a)

[1 2 3]


2.  arange() - Return an array of evenly spaced values within a given interval

In [3]:
# Create an array with 3 integers, starting from default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [4]:
# Create an array that starts from integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


3. linspace() - Here you specify the total number of points needed (num=10), and NumPy calculates the step size, whereas in arange you determine step size.

In [7]:
# Create an array that starts from 0, ends at 100 and has 5 elements in this range
d = np.linspace(0, 100, 5, dtype=int) #Not specifying dtype will return the values in float
print(d)

[  0  25  50  75 100]


In [ ]:
char_arr = np.array(['Welcome to Math for ML'])
print(char_arr)
print(char_arr.dtype) 

['Welcome to Math for ML']
<U22


1.2  More on NumPy arrays

1) np.ones() - Returns a new array setting values to one.
2) np.zeros() - Returns a new array setting values to zero.
3) np.empty() - Returns a new uninitialized array.
4) np.random.rand() - Returns a new array with values chosen at random (between 0 and 1)

In [10]:
ones_arr = np.ones(3)
zeros_array = np.zeros(3)
empty_arr = np.empty(3)
rand_arr = np.random.rand(4)
print(ones_arr)
print(zeros_array)
print(empty_arr)
print(rand_arr)

[1. 1. 1.]
[0. 0. 0.]
[ 0.00000000e+000  1.30224445e-311 -0.00000000e+000]
[0.09401109 0.73890256 0.62314672 0.6879901 ]


2  Multidimensional Arrays

Think: 
1) 1-D Array -- Vector or single ruler with markings
2) 2-D Array -- Matrix or Excel sheet
3) 3-D Array -- Stack of matrices

In [12]:
# Create a 2 dimensional array (2-D)
two_d_arr = np.array([[2, 3, 4], [2, 7, 5]])
print(two_d_arr)

[[2 3 4]
 [2 7 5]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using np.reshape() you can rearrange elements of the previous array into a new shape.

In [14]:
# 1-D array 
one_d_arr = np.array([4, 3, 9, 4, 2, 8])

# Multidimensional array using reshape()
multi_d_arr = np.reshape(
                one_d_arr, #Array to be reshaped
                (2, 3) # Dimensions of the new array
                    )
# Print the new 2-D array with 2 rows and 3 columns
print(multi_d_arr)

[[4 3 9]
 [4 2 8]]


2.1  Finding size, shape and dimension

1) ndarray.ndim - Stores the number dimensions of the array.
2) ndarray.shape - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
3) ndarray.size - Stores the number of elements in the array.

In [15]:
# Dimension of the 2-D array multi_d_arr
multi_d_arr.ndim

2

In [17]:
# Shape of the 2-D array multi_d_arr
multi_d_arr.shape

(2, 3)

In [18]:
# Size of the array multi_d_arr
multi_d_arr.size

6

3  Array Math Operations

In [19]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
